spring.application.name=tax
# Server Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/tax
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Hi?n th? chi ti?t quá trình kh?i t?o schema
logging.level.org.hibernate.tool.hbm2ddl=DEBUG

# Actuator Endpoints Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always